### ISSUE TITLE
Adding a new troubleshooting case

### ISSUE THREAD

**Issue by deltxprt** [zhliau/fika-headless-docker#24]
Hello,

Can you add this troubleshooting case in the readme.md?

I had to troubleshoot a little bit but it would save time for others to have this case in the doc. Especially for those like me who won't be playing on the server and are juste hosting it for friends.

`- Make sure you ran SPTarkov all the way to the game menu at least once before copying to another computer/server. Otherwise it will cash at the [SPT.Custom] section.`

The docker logs it self if needed for more details:

![{9D5036F7-5D31-423F-A106-A5A0406D8EA7}](https://github.com/user-attachments/assets/c96caac4-578b-4406-b5da-91be13cec848)

Thanks.

**Comment by zhliau** [comment]
I'll add this as part of #22, thanks for the heads up!

**Comment by deltxprt** [comment]
Great! Awesome work btw, keep it up!

**Comment by zhliau** [comment]
Fixed by #22
